config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :authors
  resources :books

  resources :authors do
    resources :books
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = Author.all
    render :json => @authors.to_json
  end

  def show
    @authors = Author.find(params[:id])
  end

  def create
    @authors = Author.new(author_params)

    if @authors.save
      #redirect_to @authors
      render :json => @authors.to_json
     #else
     #  render :new, status: :unprocessable_entity
    end

  end

  def update
    @authors = Author.find(params[:id])

    if @authors.update(author_params)
      redirect_to @authors
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    puts "dfg"
    @authors = Author.find(params[:id])
    @authors.destroy
    f = @authors.errors.empty?

    render :json => f.to_json
    #redirect_to authors_path
  end

  def edit
    @authors = Author.find(params[:id])
    render :json => @authors.to_json
  end

  def new
    @authors = Author.new
    render :json => @authors.to_json
  end

  private
    def author_params
      params.fetch(:author, {}).permit(:name_author)
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    render :json => @books.to_json
  end

  def create
    @authors = Author.find(params[:author_id])
    @books = @authors.books.create(book_params)
    redirect_to author_path(@authors)


  end

  def update
    @books = Book.find(params[:id])

    if @books.update(book_params)
      redirect_to @books
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @authors = Author.find(params[:author_id])
    @books = Book.find(params[:id])
    @books.destroy
    redirect_to book_path(@authors)
  end

  def edit
    @books = Book.find(params[:id])
  end

  def new
    @authors = Author.find(params[:author_id])
    @books = Book.new

  end


  private
    def book_params
      params.require(:book).permit(:name_book)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/edit.html.slim
h2 Изменение
.ui.internally.centered.grid
  .three.wide.column
    .ui.center.aligned.container
      = form_with model: @authors, class: "ui form"  do |form|

          .field

            h3.ui.header
              = form.label "Имя автора" , class: "sub header"


              = form.text_field :name_author


          .field
            = form.submit("Обновить", class: "ui tiny secondary button")

app/views/authors/index.html.slim
h2 Все авторы
p
    = link_to "Добавить автора", new_author_path
    - if @authors.count == 0
        .ui.center.header Нет не одного автора, вы можете добавить автора нажам на "Добавить атора"
    - else
    .ui.internally.centered.grid
      .five.wide.column
        .ui.center.aligned.container
          .ui.large.middle.aligned.divided.list
            - @authors.each do |author|
              .item
                .ui.two.column.relaxed.grid
                  .column
                    = link_to "Автор #{author.name_author}","/authors/#{author.id}", :class => "bottom aligned content"
                  .column
                    a.right.floated.content = button_to "Удалить", author_path(author), :class => "ui tiny secondary button", method: :delete

app/views/authors/new.html.slim
h2 Новый автор
.ui.internally.centered.grid
  .three.wide.column
    .ui.center.aligned.container
      = form_with model: @authors , class: "ui form" do |form|
        .field
          h3.ui.header
            = form.label "Имя автора", class: "sub header"
            = form.text_field :name_author
        .field
          = form.submit("Создать", class: "ui tiny secondary button")

app/views/authors/show.html.slim
h2 Автор: #{ @authors.name_author }
p
  = link_to "Все авторы","/authors"
  .ui.internally.centered.grid
    .four.wide.column
      .ui.two.item.menu
        = link_to "Редактировать автора", edit_author_path(@authors),class: "item"
        = link_to "Добавить книгу", new_author_book_path(params[:id]),class: "item"
h2 Список книг Автора: #{ @authors.name_author}
- if @authors.books.count == 0
  h3.ui.center.header У автора нет книг, нажмите на "Добавить книгу"
- else
  .ui.grid

    - @authors.books.each do |book|
      .four.wide.column
        h3 Книга: #{book.name_book}
        .image
          img src="sdvsdv.png"
        .ui.secondary.menu
          a.item = link_to "Редактировать книгу #{book.name_book}", "/books/#{book.id}/edit"
          a.item = button_to "Удалить", [book.author, book], :class => "ui tiny secondary button", method: :delete

app/views/books/edit.html.slim
h2 Изменение
.ui.internally.centered.grid
    .three.wide.column
      .ui.center.aligned.container
        = form_with model: @books, class: "ui form"  do |form|

          .field

            h3.ui.header
              = form.label "Название книги", class: "sub header"


              = form.text_field :name_book

          .field
            = form.submit("Изменить", class: "ui tiny secondary button")

app/views/books/new.html.slim
h2 Новая книга
.ui.internally.centered.grid
  .three.wide.column
    .ui.center.aligned.container
      = form_with model: [ @authors, @authors.books.build ], class: "ui form"  do |form|

        .field

            h3.ui.header
              = form.label "Название книги" , class: "sub header"


              = form.text_field :name_book


        .field
          = form.submit("Создать", class: "ui tiny secondary button")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyappBookTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all' %>

        <%= javascript_pack_tag 'application' %>
        <%= stylesheet_pack_tag 'application' %>



    <div class="ui center aligned container">
      <div class="ui text menu">
        <div class="header item">
          <h3 class="ui left aligned header">
            <font style="vertical-align: inherit;">
              <font style="vertical-align: inherit;">Книги и авторы</font>
            </font>
          </h3>
        </div>
          <%= link_to "Home", root_path,:class => "item"%>
          <%= link_to "Authors", authors_path,:class => "item"%>
      </div>
    </div>
  </head>

  <body>





<div class="ui center aligned container">
    <main>
      <%= yield %>
    </main>
</div>
  </body>
</html>

app/views/pages/index.html.erb
<div id="appp">

</div>

<h2></h2>